name: "Publish to PyPI"

on:
  release:
    types: [published]

jobs:
  semver-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Check SemVer tag
        run: |
          TAG_NAME=$(git tag --points-at ${{ github.sha }})
          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+(?:(?:[_.-])?(?:a|b|rc|alpha|beta|c|pre|preview)\d+)?(?:\.post\d+)?(?:\.dev\d+)?$ ]]; then
            echo "Valid SemVer tag: $TAG_NAME"
          else
            echo "Invalid SemVer tag: $TAG_NAME"
            exit 1
          fi
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    needs: semver-check
    steps:
      - name: Checkout code
        uses: actions/checkout@4.1.2
      - name: Set up Python 3.12
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.12"
      - name: Install build requirements
        run: >-
          python -m
          pip install -U
          pip
          build
          wheel
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
