name: "GitHub release"

on:
  push:
    tags:
      - '*.*.*' # Push events to matching semantic version tags 1.0.0, etc.

jobs:
  semver-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Check SemVer tag
        run: |
          TAG_NAME=$(git tag --points-at ${{ github.sha }})
          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
            echo "Valid SemVer tag: $TAG_NAME"
          else
            echo "Invalid SemVer tag: $TAG_NAME"
            exit 1
          fi
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ semver-check ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Set up Python 3.12
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.12"
      - name: Install build requirements
        run: |
          python -m pip install -U pip
          python -m pip install build
      - name: Build a binary wheel
        run: python -m build --outdir dist/ .
      - name: Upload release and assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: |
            dist/*.whl
